name: state_notifier_test
repository: https://github.com/danijel-tolj/state_notifier_test
description: A testing library which makes it easy to test StateNotifier. Built
  to be used with the state_notifier, riverpod or flutter_riverpod packages.
version: 0.0.9
homepage: https://that-dev.me
environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
dependencies:
  diff_match_patch: ^0.4.1
  meta: ^1.8.0
  mockito: ^5.3.2
  state_notifier: ^0.7.2+1
  test: ^1.22.1
