name: state_notifier_test
repository: https://github.com/danijel-tolj/state_notifier_test
description: A testing library which makes it easy to test StateNotifier. Built to be used with the state_notifier, riverpod or flutter_riverpod packages.
version: 0.0.1
# homepage: https://www.example.com
environment:
  sdk: '>=2.15.1 <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  build_runner: ^2.1.7
  lints: ^1.0.0
dependencies:
  diff_match_patch: ^0.4.1
  meta: ^1.7.0
  test: ^1.16.0
  mockito: ^5.0.17
  state_notifier: ^0.7.2+1
